### PR TITLE
Detects unhanded collections in OAI feed

### LINKED ISSUE #81: Detect additional Collections added to OAI-PMH

### PR DESCRIPTION
**Pull request by JPrevost**
If any Collections are detected in an OAI Harvest that are not handled,
an email is sent to sysadmins (this may want to change eventually to
instead email the appropriate Analysts but for now sysadmins works well
for us).

This also adds a feature to create Inactive Collections which is
essentially stating you have no interest in the Collection which will
prevent notification when it is detected again on a future Harvest.

closes #81

### CODE REVIEW

**Comment by richardrodgers** [comment]
:+1: for current work. Reviewing this did raise some questions that I will try to capture in another ticket. It's not the implementation, which seems fine, but rather the process model. We definitely want this for SCOAP3, so we can detect when new collections appear that are not defined. But there are other applications (e.g. pointing a harvest to PubMedCentral, or Arxiv, e.g.) where we would deliberately only want certain collections, and the burden of enumerating all that we *don't* want could greatly exceed those we *do* want. In short, some providers are 'opt-in-like' and some are 'opt-out-like'. This does a good job of handling the 'opt-out-like' cases. I'm thinking that one could add a flag on the publisher model object (maybe 'open/closed' for opt-in/opt-out), and this code could conditionalize it's work based on whether it was dealing with an open publisher, etc. The opt-in use case is what we had before this PR, so it is already implemented. Does this make sense?

**Comment by JPrevost** [comment]
I understand your reasoning and agree this should probably be switched to a toggle-able option. I'm not opposed to making that change before merging or under a new ticket for future work.

**Comment by richardrodgers** [comment]
I don't mind either option myself. I'd say since our focus is getting SCOAP3 out the door, maybe make it future work? I mostly just wanted to not forget these considerations altogether. But on the other hand, if you want to run with it, I don't think it's a huge deal. Your call.

**Comment by JPrevost** [comment]
Yeah, with that gentle reminder I'm going to just merge and we can get back to that when we move beyond SCOAP3.

**Comment by richardrodgers** [comment]
Cool thanks!

**Pull request merged**
