### PR TITLE
Adds Subscriber and Interest

### LINKED ISSUE #31: Add Subscribers and Interests
First steps in implementing subscription-based services. Multiple tickets will be entered for full functionality. This step will add subscribers and the notion of 'interests' - which are records of intent with respect to given schemes. For example, one could register a 'deliver' interest in any topics in the ORCID scheme, but a 'watch' interest in the domain affiliation. Interests will drive how subscriptions are assigned and organized.

### PR DESCRIPTION
**Pull request by richardrodgers**
Basic support for subscribers (add, edit, manage interests)
fixes #31

### CODE REVIEW

**Comment by JPrevost** [comment]
There are some UI workflow bugs that I'm not sure if we should address now or just make note of to come back and deal with later.

Ex: I can register a Interest to deliver for Orcid multiple times. If I do that, I generate RunTime errors when viewing items as they are expecting just one result returned (SingleOpt). The RunTime error is actually probably appropriate as the bug is really in the UI/Model allowing to register for the same Interest scheme/delivery preference multiple times.
`app/models/Subscriber.scala:42`

A similar (but possibly problematic) issue occurs if I setup multiple subscribers even if each just has a single Interest here:
`app/models/Subscriber.scala:83`

Totally minor, but I also can't figure out how to get back to the screen to edit my preferences after my initial Subscriber registration. (Other than changing the URL manually).

If we want to handle these concerns in future tickets that's totally fine with me.

**Comment by richardrodgers** [comment]
Thanks for the review. Let's just open new issues for these. I wanted mostly to be able to show Sean (user) what Interests look like in a UI. There's a lot of clean up, and this is a good start for locking down real behavior.

**Comment by JPrevost** [comment]
:+1:

**Comment by richardrodgers** [comment]
Yea, as to getting back to interests screen, we will need to decide where to expose in UI (you are right there is no current way). The underlying issue is that until we have a login mechanism (which would land one on one's subscriber home page), there is no natural place. But agreed, we should have a place-holder

**Comment by JPrevost** [comment]
Ok. I'll open tickets for those three things in M2 and merge this.

**Pull request merged**
