### PR TITLE
Extracts common pagination logic into a tag

### PR DESCRIPTION
**Pull request by JPrevost**

### CODE REVIEW

**Comment by JPrevost** [comment]
@richardrodgers I opened this to get some feedback on whether this is something we want to do or not. If it is, I'll add some additional styling work (minor as I know this isn't our core concern).

It "solves" my problem of passing a partial route to the tag by just avoiding that problem entirely. This cleans up the views, but skips the routing helper. So... yeah.

**Comment by richardrodgers** [comment]
@JPrevost I like this - definitely wins DRY points. My only suggestion is that we eliminate the hardcoded paths (which the routes API is meant to encourage). Because of a quirk of the resolution machinery that allows for default values (in this case page #), I'm pretty sure we can replace:

@tags.pagination(page, 10, total, "/items/browse?filter=topic&id=".concat(id.toString), items.length)

with:

@tags.pagination(page, 10, total, routes.Application.itemBrowse(filter, id).toString, items.length)

etc in all other contexts of occurance

**Comment by JPrevost** [comment]
Thanks!

**Comment by JPrevost** [comment]
@richardrodgers You okay with me squashing the extra commit and merging this?

**Comment by richardrodgers** [comment]
Go right ahead

**Pull request merged**
